config/routes.rb
Rails.application.routes.draw do  
  devise_for :users , controllers: {
        registrations: 'users/registrations'
      }
  get 'app/list', to: 'apps#list'
  get 'tops', to: 'apps#top'
  resources :apps
=begin
  resources :apps do
  	member do
  		resources :photos,only: [:create,:destroy]
  	end
  end
=end
  resources :stores,:makers,:categories,:apptypes,:reviews,:kuchikomis
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "apps#index"
  mount ActionCable.server => '/cable'#khong co dong nay thi AC broadcast du lieu nhung cacs client se khong nhan duoc gi dau.
end

app/models/app.rb
class App < ApplicationRecord
	mount_uploader :picture, PictureUploader
  mount_uploaders :photos, PhotoUploader
  serialize :photos, JSON
  belongs_to :maker
  belongs_to :store
  belongs_to :user
  belongs_to :category
  belongs_to :apptype
  has_many :reviews
  has_many :reviewed_users,through: :reviews,source: :user,dependent: :destroy
  has_many :photos
  has_many :kuchikomis  
  validates :name,presence: true,uniqueness: true
  validates :originid,presence: true,uniqueness: {scope: :store}
  validates :link,presence: true

  def rating
  	avg = reviews.average(:value)
    if avg
      return avg
    else
      return 0
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/apptype.rb
class Apptype < ApplicationRecord
	validates :name,presence: true,uniqueness: true
	has_many :apps,dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name,presence: true,uniqueness: true
	has_many :apps,dependent: :destroy
end

app/models/keyword.rb
class Keyword < ApplicationRecord
end

app/models/kuchikomi.rb
class Kuchikomi < ApplicationRecord
  belongs_to :user
  belongs_to :app
  validates :text,presence: true
end

app/models/maker.rb
class Maker < ApplicationRecord
	validates :name,presence: true,uniqueness: true
	has_many :apps,dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :app
  validates :text,presence: true
  validates :value,presence: true,numericality: {greater_than: 0,less_than: 6}
end

app/models/source.rb
class Source < ApplicationRecord
  belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord
	validates :name,presence: true,uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :reviews,dependent: :destroy
	has_many :kuchikomis,dependent: :destroy
	has_many :apps
	mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  validates :name,presence: true,uniqueness: true
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
	def star_rating_for value		
		if value
			html="<span style='color: #fde16d;'>"
			value=(value.round(1)*2).round/2.0
			while value>0.5
				value-=1.0
				html+="<span class='fa fa-star'></span>"
			end
			html+="<span class='fa fa-star-half-o'></span>" if value>0
			raw(html+'</span>')
		else
			raw t('views.app.no_review')
		end				
	end
end

app/helpers/apptypes_helper.rb
module ApptypesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h4>#{sentence}</h4>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

  def errors_for resource,attribute
    messages = resource.errors.full_messages_for(attribute) { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
      <div class="feedback">
        <ul>#{messages}</ul>
      </div>
    HTML
    html.html_safe
  end
end

app/helpers/kuchikomis_helper.rb
module KuchikomisHelper
end

app/helpers/makers_helper.rb
module MakersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/apps/_app.html.erb
<div class="card-deck">
                    <div class="card" >
                      <%= image_tag app.picture.url, class: "card-img-top" %>
                      <div class="card-block">
                        <h4 class="card-title"><%= link_to app.name, app %></h4>
                        <span><%=star_rating_for app.reviews.average(:value)%></span>(<%= app.reviews.count %>)
                      </div>
                    </div>
                  </div>

app/views/apps/_app_comments.html.erb
<div id="comment_form" class="row well">
  <% if user_signed_in? %>
      <h4>
        <b>コメントしてください</b>
      </h4>
      <%= form_for Kuchikomi.new, remote: true do |f| %>
          <%= f.hidden_field :app_id, value: @app.id %>

          <div class="form-group " class="col-md-6 col-md-offset-3">
            <%= f.text_field :text, class: "form-control", placeholder: "コメントしてください" %>
            <div class="invalid-feedback" id="text_feedback"></div>
          </div>
          <div class="form-group">
            <%= f.submit :class => 'btn btn-success' %>
          </div>
      <% end %>
  <% end %>
</div>
<div class="row well">
  <div id="app_<%= @app.id %>_kuchikomis">
    <%= render @app.kuchikomis.order(created_at: :desc) %>
  </div>
</div>

app/views/apps/_app_overview.html.erb
<br>
<div id="description" class="row">
  <h3>概要</h3>
  <p>
    <%= @app.description %>
  </p>
  <h4>Tag</h4>
  <span class="label label-info">
        <%= @app.category.name %>
    </span>
  <span class="label label-info">
        <%= @app.apptype.name %>
    </span>
  <span class="label label-info">
        <%= @app.store.name %>
    </span>
  <span class="label label-info">
        <%= @app.maker.name %>
    </span>
  <br><br>
</div>
<% if @app.photos.length > 0 %>
    <div class="row">
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <% @app.photos.each_with_index do |photo, index| %>
              <div class="item <%= 'active' if index == 1 %>">
                <%= image_tag photo.url, alt: "application screenshot", style: "width:100%;" %>
              </div>
          <% end %>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
<% end %>
<div class="row">

</div>

app/views/apps/_app_reviews_tab.html.erb
<br>
<div class="row well">
  <div class="row">
    <div class="col-md-10">
      <div class="">
        <div class="row">
          <div class="col-xs-6 col-md-6 text-center">
            <h1 class="rating-num">
              <%=@avg_rate %></h1>
            <div class="rating" style="font-size:36px">
              <%=star_rating_for @avg_rate%>
            </div>
            <div>
              <span class="glyphicon glyphicon-user"></span><%= @app.reviews.count %> レビュー
            </div>
          </div>
          <div class="col-xs-6 col-md-6">
            <div class="row rating-desc">
              <div class="col-xs-3 col-md-3 text-right">
                <span class="glyphicon glyphicon-star"></span>5
              </div>
              <div class="col-xs-8 col-md-9">
                <div class="progress progress-striped">
                  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="20"
                       aria-valuemin="0" aria-valuemax="100" style="width: <%=@five_rate_percent %>%">
                    <span class="sr-only"><%=@five_rate_percent %>%</span>
                  </div>
                </div>
              </div>
              <!-- end 5 -->
              <div class="col-xs-3 col-md-3 text-right">
                <span class="glyphicon glyphicon-star"></span>4
              </div>
              <div class="col-xs-8 col-md-9">
                <div class="progress">
                  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="20"
                       aria-valuemin="0" aria-valuemax="100" style="width: <%=@four_rate_percent %>%">
                    <span class="sr-only"><%=@four_rate_percent %>%</span>
                  </div>
                </div>
              </div>
              <!-- end 4 -->
              <div class="col-xs-3 col-md-3 text-right">
                <span class="glyphicon glyphicon-star"></span>3
              </div>
              <div class="col-xs-8 col-md-9">
                <div class="progress">
                  <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20"
                       aria-valuemin="0" aria-valuemax="100" style="width: <%=@three_rate_percent %>%">
                    <span class="sr-only"><%=@three_rate_percent %>%</span>
                  </div>
                </div>
              </div>
              <!-- end 3 -->
              <div class="col-xs-3 col-md-3 text-right">
                <span class="glyphicon glyphicon-star"></span>2
              </div>
              <div class="col-xs-8 col-md-9">
                <div class="progress">
                  <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="20"
                       aria-valuemin="0" aria-valuemax="100" style="width: <%=@two_rate_percent %>%">
                    <span class="sr-only"><%=@two_rate_percent %>%</span>
                  </div>
                </div>
              </div>
              <!-- end 2 -->
              <div class="col-xs-3 col-md-3 text-right">
                <span class="glyphicon glyphicon-star"></span>1
              </div>
              <div class="col-xs-8 col-md-9">
                <div class="progress">
                  <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80"
                       aria-valuemin="0" aria-valuemax="100" style="width: <%=@one_rate_percent %>%">
                    <span class="sr-only"><%=@one_rate_percent %>%</span>
                  </div>
                </div>
              </div>
              <!-- end 1 -->
            </div>
            <!-- end row -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row well">
  <div class="col-md-11 col-md-offset-1 ">
    <%= render 'reviews/form' %>
  </div>
</div>
<div class="row well">
  <div class="col-sm-7">
    <hr/>
    <div id="app_<%= @app.id %>_reviews" class="review-block">
      <%= render @app.reviews %>
    </div>
  </div>
</div>

app/views/apps/create.js.erb
<% error_attributes=@app.errors.keys%>
<% [:name,:maker,:store,:originid,:link,:category,:apptype].each do |attribute|%>
	$("form#new_app #<%=attribute%>_feedback").empty()
	$("form#new_app #app_<%=attribute%>").removeClass('is-invalid')
	<% if error_attributes.include? attribute %>
		$("form#new_app #app_<%=attribute%>").addClass('is-invalid')		
		<% @app.errors.full_messages_for(attribute).each do |msg| %>
			$("form#new_app #<%=attribute%>_feedback").append("<li><%=msg%></li>")
		<% end %>
	<% end %>				
<% end %>

app/views/apps/edit.html.erb
<div class="row">
  <div class="col-md-4 mx-auto">
    <h1><%= t 'views.app.new_app' %></h1>
  </div>
</div>
<br>
<div class="row">
  <div class="">
    <%= render 'apps/form' %>
  </div>
</div>

app/views/apps/index.html.erb
<div class="row" style="border: #aaaaaa">
  <div class="col-6 col-md-2 sidebar-offcanvas ml-5" id="sidebar">
    <div id="type" style="display: none"><%=@type%></div>
    <div class="list-group">
      <%=text_field_tag :value,nil,placeholder: "検索",class: 'form-control'%>     
      <%=link_to 'アプリ',apps_path(type: 'name'),id: 'name',remote: true,class: 'list-group-item'%>
      <%=link_to 'カテゴリー',apps_path(type: 'category'),id: 'category',remote: true,class: 'list-group-item'%>
      <%=link_to 'メーカー',apps_path(type: 'maker'),id: 'maker',remote: true,class: 'list-group-item'%>
      <br>
      <br>
      <a id="top" class="btn btn-link" style="text-decoration: underline;">ランキング</a>      
    </div>
  </div>
  <div class="col-md-9" id="apps">
    <% @categories.each do |category| %>
    <div id="category_<%=category.id%>" class="eachCategory">
      <% zenbu_apps = @apps.where(category_id: category.id) %>
      <% sukoshi_apps = zenbu_apps[0..5] %>    
    
      <% if sukoshi_apps.length > 0 %>
        <h3><%= category.name %></h3>
        <div class="row" style="background-color: #FAFAFA" id="sukoshi">
          <% sukoshi_apps.each do |app| %>
            <div class="card-deck col-md-2">
              <div class="card" >
                <%= image_tag app.picture.url, class: "card-img-top" %>
                <div class="card-block">
                  <h4 class="card-title"><%= link_to app.name, app %></h4>
                  <span><%=star_rating_for app.reviews.average(:value)%></span>(<%= app.reviews.count %>)
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
      <% if zenbu_apps.length > 6%>
        <div class="row" style="background-color: #FAFAFA;display: none" id="zenbu">
          <% zenbu_apps.each do |app| %>
            <div class="card-deck col-md-2">
              <div class="card" >
                <%= image_tag app.picture.url, class: "card-img-top" %>
                <div class="card-block">
                  <h4 class="card-title"><%= link_to app.name, app %></h4>
                  <span><%=star_rating_for app.reviews.average(:value)%></span>(<%= app.reviews.count %>)
                </div>
              </div>
            </div>
          <% end %>
        </div>        
        <div class="col-md-1 col-md-offset-11">          
          <a id="readmore_<%=category.id%>" class="btn btn-link readmore" style="text-decoration: underline;">もっと見る</a>
        </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/apps/index.js.erb
$('#sidebar a').removeClass('active')
$('#sidebar a#<%=@type%>').addClass('active')

app/views/apps/list.html.erb
<style>
  .filterable {
    margin-top: 15px;
  }
  .filterable .panel-heading .pull-right {
    margin-top: -20px;
  }
  .filterable .filters input[disabled] {
    background-color: transparent;
    border: none;
    cursor: auto;
    box-shadow: none;
    padding: 0;
    height: auto;
  }
  .filterable .filters input[disabled]::-webkit-input-placeholder {
    color: #333;
  }
  .filterable .filters input[disabled]::-moz-placeholder {
    color: #333;
  }
  .filterable .filters input[disabled]:-ms-input-placeholder {
    color: #333;
  }
  a:visited {
    color: red;
  }
</style>
<script type="text/javascript" charset="utf-8">
    /*
    Please consider that the JS part isn't production ready at all, I just code it to show the concept of merging filters and titles together !
    */
    $(document).ready(function(){
        $('.filterable .btn-filter').click(function(){
            var $panel = $(this).parents('.filterable'),
                $filters = $panel.find('.filters input'),
                $tbody = $panel.find('.table tbody');
            if ($filters.prop('disabled') == true) {
                $filters.prop('disabled', false);
                $filters.first().focus();
            } else {
                $filters.val('').prop('disabled', true);
                $tbody.find('.no-result').remove();
                $tbody.find('tr').show();
            }
        });

        $('.filterable .filters input').keyup(function(e){
            /* Ignore tab key */
            var code = e.keyCode || e.which;
            if (code == '9') return;
            /* Useful DOM data and selectors */
            var $input = $(this),
                inputContent = $input.val().toLowerCase(),
                $panel = $input.parents('.filterable'),
                column = $panel.find('.filters th').index($input.parents('th')),
                $table = $panel.find('.table'),
                $rows = $table.find('tbody tr');
            /* Dirtiest filter function ever ;) */
            var $filteredRows = $rows.filter(function(){
                var value = $(this).find('td').eq(column).text().toLowerCase();
                return value.indexOf(inputContent) === -1;
            });
            /* Clean previous no-result if exist */
            $table.find('tbody .no-result').remove();
            /* Show all rows, hide filtered ones (never do that outside of a demo ! xD) */
            $rows.show();
            $filteredRows.hide();
            /* Prepend no-result row if all rows are filtered */
            if ($filteredRows.length === $rows.length) {
                $table.find('tbody').prepend($('<tr class="no-result text-center"><td colspan="'+ $table.find('.filters th').length +'">No result found</td></tr>'));
            }
        });
    });
</script>
<div class="row">
  <div class="panel panel-primary filterable">
    <div class="panel-heading">
      <h3 class="panel-title">アプリケーション</h3>
      <div class="pull-right">
        <button class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-filter"></span> Filter</button>
      </div>
    </div>
    <table class="table">
      <thead>
      <tr class="filters">
        <th><input type="text" class="form-control" placeholder="ID" disabled></th>
        <th><input type="text" class="form-control" placeholder="名" disabled></th>
        <th><input type="text" class="form-control" placeholder="メーカ" disabled></th>
        <th><input type="text" class="form-control" placeholder="アクション" disabled></th>
      </tr>
      </thead>
      <tbody>
      <% @apps.each do |app| %>
      <tr>
        <td><%= app.id %></td>
        <td><%= app.name %></td>
        <td><%= app.maker.name %></td>
        <td>
          <%= link_to '変更',edit_app_path(app), class: "btn btn-link" %>
          <%= link_to "削除", app, method: :delete,
                      data: { confirm: "You sure?" }, class: 'btn btn-link' %>
        </td>
      </tr>
          <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/apps/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-5">
    <h1><%= t 'views.app.new_app' %></h1>
  </div>
</div>
<br>
<div class="row">
    <%= render 'apps/form'  %>
</div>

app/views/apps/show.html.erb
<style>


  .review-block {
    background-color: #f5f5f5;
    border: 1px solid #EFEFEF;
    padding: 15px;
    border-radius: 3px;
    margin-bottom: 15px;
  }
  .glyphicon { margin-right:5px;}
  .rating .glyphicon {font-size: 22px;}
  .rating-num { margin-top:0px;font-size: 54px; }
  .progress { margin-bottom: 5px;}
  .progress-bar { text-align: left; }
  .rating-desc .col-md-3 {padding-right: 0px;}
  .sr-only { margin-left: 5px;overflow: visible;clip: auto; }
</style>
<div class="row">
  <div class="col-md-10">
    <!-- Thông tin trên cùng -->
    <div>
      <div class="review-block">
        <div class="media">
          <div class="media-left col-md-2">
            <%= image_tag @app.picture.url, width: "100%", class: "media-object" %>
          </div>
          <div class="media-body">
            <h1 class="media-heading">
              <%= @app.name %>
            </h1>
          </div>

          <br>
          <h4>
            <%= t('views.app.by', maker: @app.maker.try(:name)||"メーカー名") %>
          </h4>
          <button type="button" class="btn btn-success">Review
            <span class="badge"><%= @app.reviews.count %></span>
          </button>
          <a href="#">
            <span><%=link_to '',edit_app_path(@app),class: 'btn btn-success fa fa-external-link'%></span>        
            <%= link_to "ダウンロードページヘ", @app.link, target: "_blank", class: "btn btn-secondary" %>
          </a>
        </div>
      </div>
    </div>
    <br>
    <hr>

    <!-- 3 cái nút -->
    <ul class="nav nav-pills nav-justified" role="tablist">
      <li class="nav-item active">
        <a class="nav-link active review-block" data-toggle="pill" href="#overview">概要</a>
      </li>
      <li class="nav-item">
        <a class="nav-link review-block" data-toggle="pill" href="#reviews">レビュー</a>
      </li>
      <li class="nav-item">
        <a class="nav-link review-block" data-toggle="pill" href="#comments">コメント(<%=@app.kuchikomis.size%>)</a>
      </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">


      <div id="overview" class=" tab-pane active">
        <div class="col-md-10 col-md-offset-1">
          <%= render 'apps/app_overview' %>
        </div>
      </div>

      <!-- Phần reviews -->
      <div id="reviews" class="container tab-pane fade">
        <div class="row">
          <div class="col-md-10">
            <%= render 'app_reviews_tab' %>
          </div>
        </div>
      </div>
      <!-- Phần Comments -->

      <div id="comments" class="container tab-pane fade">
        <br>
        <div class="col-md-10">
          <%= render 'app_comments' %>
        </div>

      </div>
      <hr>
      <!-- /container -->

    </div>
  </div>
  <div class="col-md-2" style="background-color: #FAFAFA">
    <h2>関連アプリ</h2>
    <%=render @kanren_apps%>
  </div>
</div>

app/views/apps/top.html.erb
<div class="row" style="border: #aaaaaa">  
  <div class="col-md-9" id="apps">
    <% if @high_rate_apps.length > 0 %> <h3>評価</h3>

            <div class="row" style="background-color: #FAFAFA">
              <% @high_rate_apps.each do |app| %>
                  <div class="card-deck col-md-2">
                    <div class="card" >
                      <%= image_tag app.picture.url, class: "card-img-top" %>
                      <div class="card-block">
                        <h4 class="card-title"><%= link_to app.name, app %></h4>
                        <span><%=star_rating_for app.reviews.average(:value)%></span>(<%= app.reviews.count %>)
                      </div>
                    </div>
                  </div>

              <% end %>
            </div>            
    <% end %>
    <% if @high_comment_apps.length > 0 %> <h3>口コミ</h3>

            <div class="row" style="background-color: #FAFAFA">
              <% @high_comment_apps.each do |app| %>
                  <div class="card-deck col-md-2">
                    <div class="card" >
                      <%= image_tag app.picture.url, class: "card-img-top" %>
                      <div class="card-block">
                        <h4 class="card-title"><%= link_to app.name, app %></h4>
                        <span><%=star_rating_for app.reviews.average(:value)%></span>(<%= app.reviews.count %>)
                      </div>
                    </div>
                  </div>

              <% end %>
            </div>            
    <% end %>    
  </div>
</div>

app/views/apps/update.js.erb
<% @updated_params.each do |form_id| %>
	$('input[form="<%=form_id%>"]').attr("style",'display:none')
<% end %>

app/views/layouts/_footer.html.erb
<hr />
<div class="text-center center-block">
    <p class="txt-railway">- Taiyou.com -</p>
    <br />
    <a href="https://www.facebook.com/bootsnipp">
        <i class="fa fa-facebook-square fa-3x social"></i>
    </a>
    <a href="https://twitter.com/bootsnipp">
        <i class="fa fa-twitter-square fa-3x social"></i>
    </a>
    <a href="https://plus.google.com/+Bootsnipp-page">
        <i class="fa fa-google-plus-square fa-3x social"></i>
    </a>
    <a href="mailto:bootsnipp@gmail.com">
        <i class="fa fa-envelope-square fa-3x social"></i>
    </a>
</div>
<hr />

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">

      <%= link_to  root_path, class: "navbar-brand" do%>
          <%= image_tag 'logo.png', style: "max-width: 20%"%>
      <% end%>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span><%=image_tag current_user.avatar,size: "40x40",class: "avatar"%></span>
              <strong><%= current_user.name %></strong><span id="current_user_id" style="display: none"><%=current_user.id%></span>
              <span class="glyphicon glyphicon-chevron-down"></span>
            </a>
          <ul class="dropdown-menu">
            <li class="nav-item">
              <%=link_to t("新しいアプリ"),new_app_path,class: "nav-link glyphicon glyphicon-plus-sign" if user_signed_in? %>
              <%=link_to t('profile'),edit_user_registration_path,class: "nav-link fa fa-user dropdown-item" if user_signed_in? %>
            </li>
            <li class="nav-item">
              <%=link_to "アプリ一覧",app_list_path,class: "nav-link glyphicon glyphicon-list-alt" if user_signed_in?&&current_user.admin? %>
            </li>
            <li class="nav-item">
              <%=link_to t("views.maker.maker_list"),makers_path,class: "nav-link fa fa-window-restore dropdown-item" if user_signed_in?&&current_user.admin? %>
            </li>
            <li class="nav-item">
              <%=link_to t("views.store.store_list"),stores_path,class: "nav-link fa fa-cart-plus dropdown-item" if user_signed_in?&&current_user.admin? %>
            </li>
            <li class="nav-item">
              <%=link_to t("views.category.category_list"),categories_path,class: "nav-link" if user_signed_in?&&current_user.admin? %>
            </li>
            <li class="nav-item">
              <%=link_to t("views.apptype.apptype_list"),apptypes_path,class: "nav-link" if user_signed_in?&&current_user.admin? %>
            </li>
            <li class="nav-item">
              <%=link_to t("sign_up"),new_user_registration_path,class: "nav-link fa fa-user-plus dropdown-item" if !user_signed_in? %>
            </li>
            <li class="nav-item">
              <%=link_to t("log_in"),new_user_session_path,class: "nav-link fa fa-sign-in dropdown-item" if !user_signed_in? %>
            </li>
            <li class="nav-item">
              <%=link_to t("sign_out"),destroy_user_session_path,method: :delete,class: "nav-link fa fa-sign-out dropdown-item" if user_signed_in? %>
            </li>
          </ul>
        </li>
      <% else %>
      <li>
        <%=link_to t("sign_up"),new_user_registration_path,class: "nav-link fa fa-user-plus dropdown-item" %>
      </li>
      <li>
        <%=link_to t("log_in"),new_user_session_path,class: "nav-link fa fa-sign-in dropdown-item"  %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>
    <%= t('websitename') %>
  </title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-star-rating/4.0.2/css/star-rating.min.css"
  />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
</head>

<body style="background-color:#eeeeee">
<%= render 'layouts/header' %>
<div class="container" style="background-color:white">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <% if notice %>
          <p class="notice" id="notice">
            <%= notice %>
          </p>
      <% end %>
      <% if alert %>
          <p class="alert" id="alert">
            <%= alert %>
          </p>
      <% end %>
    </div>
  </div>
  <div class="row">
    <%= yield %>
  </div>
</div>
<%= render 'layouts/footer' %>
</body>

</html>